use std::fs;
use std::path::{Path, PathBuf};
use std::time::UNIX_EPOCH;

use jikji_core::{JIKJI_DIR, JikjiError, PrepareOptions, Result, io_error};
use serde::Serialize;
use sha2::{Digest, Sha256};

const DEFAULT_IGNORE_PATTERNS: &[&str] =
    &["~$*", "Thumbs.db", ".DS_Store", "desktop.ini", "kaggle"];
const SENSITIVE_PATTERNS: &[&str] = &[
    ".git",
    ".hg",
    ".svn",
    "node_modules",
    "__pycache__",
    ".venv",
    "venv",
    ".env",
    ".env.*",
    "id_rsa",
    "id_dsa",
    "id_ecdsa",
    "id_ed25519",
    "*.pem",
    "*.key",
    "*.p12",
    "*.pfx",
];
const AGENT_RULES_BEGIN: &str = "<!-- BEGIN JIKJI ROUTING (auto-generated by `jikji prepare`; do not edit inside this block) -->";
const AGENT_RULES_END: &str = "<!-- END JIKJI ROUTING -->";
const AGENT_RULE_FILES: &[&str] = &["AGENTS.md", "CLAUDE.md", ".cursorrules"];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScanResult {
    pub root: PathBuf,
    pub files: Vec<PathBuf>,
    pub dirs: Vec<PathBuf>,
    pub truncated: bool,
    pub signature: SourceTreeSignature,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct SourceTreeSignature {
    pub algorithm: &'static str,
    pub digest: String,
    pub files: usize,
    pub folders: usize,
    pub total_size: u64,
    pub max_mtime_ns: u128,
}

pub fn scan_root(root: &Path, options: &PrepareOptions) -> Result<ScanResult> {
    let clean_root = root
        .canonicalize()
        .map_err(|source| io_error(root, source))?;
    if !clean_root.is_dir() {
        return Err(JikjiError::NotDirectory(clean_root));
    }

    let mut state = ScanState::new(options.clone(), clean_root.clone());
    state.walk(&clean_root)?;
    state.files.sort();
    state.dirs.sort();
    let signature = source_tree_signature(&clean_root, &state.files, &state.dirs);

    Ok(ScanResult {
        root: clean_root,
        files: state.files,
        dirs: state.dirs,
        truncated: state.truncated,
        signature,
    })
}

struct ScanState {
    options: PrepareOptions,
    root: PathBuf,
    files: Vec<PathBuf>,
    dirs: Vec<PathBuf>,
    truncated: bool,
}

impl ScanState {
    fn new(options: PrepareOptions, root: PathBuf) -> Self {
        Self {
            options,
            root,
            files: Vec::new(),
            dirs: Vec::new(),
            truncated: false,
        }
    }

    fn walk(&mut self, current: &Path) -> Result<()> {
        if self.truncated {
            return Ok(());
        }
        let entries = match fs::read_dir(current) {
            Ok(entries) => entries,
            Err(error) if error.kind() == std::io::ErrorKind::PermissionDenied => return Ok(()),
            Err(source) => return Err(io_error(current, source)),
        };
        for entry in entries {
            if self.truncated {
                return Ok(());
            }
            let entry = match entry {
                Ok(entry) => entry,
                Err(error) if error.kind() == std::io::ErrorKind::PermissionDenied => continue,
                Err(source) => return Err(io_error(current, source)),
            };
            let name = entry.file_name().to_string_lossy().into_owned();
            let path = entry.path();
            if self.skip_entry(&path, &name) {
                continue;
            }
            let file_type = match entry.file_type() {
                Ok(file_type) => file_type,
                Err(_) => continue,
            };
            if file_type.is_symlink() {
                continue;
            }
            if file_type.is_dir() {
                self.dirs.push(path.clone());
                self.walk(&path)?;
                continue;
            }
            if file_type.is_file() {
                if is_pure_generated_agent_rule(&path, &name)? {
                    continue;
                }
                if self
                    .options
                    .max_files
                    .is_some_and(|limit| self.files.len() >= limit)
                {
                    self.truncated = true;
                    return Ok(());
                }
                self.files.push(path);
            }
        }
        Ok(())
    }

    fn skip_entry(&self, path: &Path, name: &str) -> bool {
        if name == JIKJI_DIR {
            return true;
        }
        let rel = rel_path(&self.root, path);
        self.options
            .exclude_patterns
            .iter()
            .any(|pattern| glob_match(pattern, name) || glob_match(pattern, &rel))
            || DEFAULT_IGNORE_PATTERNS
                .iter()
                .any(|pattern| glob_match(pattern, name))
            || (!self.options.include_hidden && name.starts_with('.'))
            || (!self.options.include_sensitive
                && SENSITIVE_PATTERNS
                    .iter()
                    .any(|pattern| glob_match(pattern, name)))
    }
}

fn is_pure_generated_agent_rule(path: &Path, name: &str) -> Result<bool> {
    if !AGENT_RULE_FILES.contains(&name) {
        return Ok(false);
    }
    let text = fs::read_to_string(path).map_err(|source| io_error(path, source))?;
    let trimmed = text.trim();
    Ok(trimmed.starts_with(AGENT_RULES_BEGIN) && trimmed.ends_with(AGENT_RULES_END))
}

fn source_tree_signature(root: &Path, files: &[PathBuf], dirs: &[PathBuf]) -> SourceTreeSignature {
    let mut hasher = Sha256::new();
    let mut file_count = 0usize;
    let mut total_size = 0u64;
    let mut max_mtime_ns = 0u128;

    for path in files {
        let metadata = match fs::metadata(path) {
            Ok(metadata) => metadata,
            Err(_) => continue,
        };
        let rel = rel_path(root, path);
        let size = metadata.len();
        let mtime_ns = metadata_mtime_ns(&metadata);
        file_count += 1;
        total_size = total_size.saturating_add(size);
        max_mtime_ns = max_mtime_ns.max(mtime_ns);
        hasher.update(rel.as_bytes());
        hasher.update(b"\0");
        hasher.update(size.to_string().as_bytes());
        hasher.update(b"\0");
        hasher.update(mtime_ns.to_string().as_bytes());
        hasher.update(b"\n");
    }

    SourceTreeSignature {
        algorithm: "sha256(relpath,size,mtime_ns).v1",
        digest: format!("{:x}", hasher.finalize()),
        files: file_count,
        folders: dirs.len() + 1,
        total_size,
        max_mtime_ns,
    }
}

pub(crate) fn rel_path(root: &Path, path: &Path) -> String {
    jikji_core::path_text(
        &path
            .strip_prefix(root)
            .unwrap_or(path)
            .to_string_lossy()
            .replace(std::path::MAIN_SEPARATOR, "/"),
    )
}

pub(crate) fn metadata_mtime_ns(metadata: &fs::Metadata) -> u128 {
    metadata
        .modified()
        .ok()
        .and_then(|modified| modified.duration_since(UNIX_EPOCH).ok())
        .map_or(0, |duration| duration.as_nanos())
}

pub(crate) fn glob_match(pattern: &str, value: &str) -> bool {
    let pattern = pattern.trim_start_matches("./");
    let value = value.trim_start_matches("./").trim_end_matches('/');
    if let Some(dir) = pattern.strip_suffix("/**") {
        let dir = dir.trim_end_matches('/');
        return !dir.is_empty() && (value == dir || value.starts_with(&format!("{dir}/")));
    }
    if let Some(dir) = pattern.strip_suffix("/*") {
        let dir = dir.trim_end_matches('/');
        if dir.is_empty() {
            return !value.contains('/');
        }
        if value == dir {
            return true;
        }
        return value
            .strip_prefix(&format!("{dir}/"))
            .is_some_and(|rest| !rest.is_empty() && !rest.contains('/'));
    }
    match (pattern.strip_prefix('*'), pattern.strip_suffix('*')) {
        (Some(suffix), _) => value.ends_with(suffix),
        (_, Some(prefix)) => value.starts_with(prefix),
        _ if pattern.contains('*') => {
            let mut parts = pattern.split('*');
            let prefix = parts.next().unwrap_or_default();
            let suffix = parts.next_back().unwrap_or_default();
            value.starts_with(prefix) && value.ends_with(suffix)
        }
        _ => pattern == value,
    }
}

#[cfg(test)]
mod tests {
    use super::{glob_match, scan_root};
    use jikji_core::PrepareOptions;
    use std::fs;

    #[test]
    fn scan_skips_kaggle_dataset_directories() {
        let dir = tempfile::tempdir().expect("tempdir");
        fs::write(dir.path().join("brief.pdf"), "%PDF").expect("pdf");
        fs::create_dir_all(dir.path().join("kaggle/train_images")).expect("kaggle dir");
        fs::write(
            dir.path().join("kaggle/train_images/1029778366.jpg"),
            b"jpeg-bytes",
        )
        .expect("jpg");
        let scan = scan_root(dir.path(), &PrepareOptions::default()).expect("scan");
        let rels: Vec<String> = scan
            .files
            .iter()
            .map(|path| super::rel_path(dir.path(), path))
            .collect();
        assert_eq!(rels, vec!["brief.pdf".to_string()]);
    }

    #[test]
    fn glob_match_tmp_starstar_matches_directory_and_descendants() {
        assert!(glob_match("tmp/**", "tmp"));
        assert!(glob_match("tmp/**", "tmp/secret.txt"));
        assert!(glob_match("tmp/**", "tmp/nested/a.txt"));
        assert!(glob_match("keep/tmp/**", "keep/tmp"));
        assert!(glob_match("keep/tmp/**", "keep/tmp/secret.txt"));
        assert!(!glob_match("tmp/**", "keep/hello.txt"));
        assert!(!glob_match("tmp/**", "secret.txt"));
        assert!(!glob_match("keep/tmp/**", "tmp"));
        assert!(glob_match("kaggle", "kaggle"));
        assert!(glob_match("~$*", "~$book.xlsx"));
        assert!(glob_match("*.tmp", "foo.tmp"));
    }

    #[test]
    fn scan_skips_excluded_tmp_starstar_directories() {
        let dir = tempfile::tempdir().expect("tempdir");
        fs::create_dir_all(dir.path().join("keep")).expect("keep");
        fs::create_dir_all(dir.path().join("tmp/nested")).expect("tmp");
        fs::write(dir.path().join("keep/hello.txt"), "hello").expect("keep file");
        fs::write(dir.path().join("tmp/secret.txt"), "secret").expect("tmp file");
        fs::write(dir.path().join("tmp/nested/hidden.txt"), "hidden").expect("nested tmp");
        let options = PrepareOptions {
            exclude_patterns: vec!["tmp/**".to_owned()],
            ..PrepareOptions::default()
        };
        let scan = scan_root(dir.path(), &options).expect("scan");
        let rels: Vec<String> = scan
            .files
            .iter()
            .map(|path| super::rel_path(dir.path(), path))
            .collect();
        assert_eq!(rels, vec!["keep/hello.txt".to_string()]);
        assert!(
            !scan.dirs.iter().any(|path| path.ends_with("tmp")),
            "excluded tmp directory must not be scanned: {:?}",
            scan.dirs
        );
    }
}
